spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 159753
    username: root