spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 159753
    driver-class-name: com.mysql.cj.jdbc.Driver